flatcar/flatcar-docs

.gitmodules

This updates the submodule URL and picks the last commits.

Update submodule: container-linux-config-transpiler

---

os/migrate-from-container-linux.md

This reflects the current state of variables with
the stable release.

Migration: State required and recommended changes

---

os/booting-on-azure.md

Official images are available now through the
Marketplace.
Leave the information on how to upload own images
there for now.

Azure: Document official images

---

index.md
os/booting-on-packet.md
os/quickstart.md

Packet was totally hidden, the other were available via searching or clicking forward but not in the navigation menu.
Also update the Packet docs.

Make all platforms visible, update Packet docs

---

index.md
os/booting-on-vagrant.md
os/booting-on-virtualbox.md

Mark platforms that we do not cover with our release tests
as unsupported.

Add a note for unsupported platforms

---

ignition/boot-process.md

This question came up on IRC and since systemd presets are not mentioned
and resetting the presets is also not easy, just document how a symlink
can be used to ensure that a service is enabled.

Ignition: Document how to enable systemd services when reprovisioning

---

os/install-debugging-tools.md

The toolbox can only run once and it's not easy to run a background
process or share a session.
Document how to do that with some tricks.
See commands.
Tested in a VM with multiple SSH connections that attach to the tmux session.

toolbox: Document how to run tmux in the background and attach to it

---

os/sdk-modifying-flatcar.md

The existing docs were too brief and started with some confusing advice
to set up a password which is not really needed in most cases.
Give more context on how things work and instruct on preparing the
correct build branches and binary package references.

Improve documentation on building Flatcar

---

os/customizing-docker.md

Changed the word "with" to "the". Sorry this is not more interesting :).
Just read the docs and you will notice the change.
Proof read the doc after making the change.

Super minor(1 word) doc wording fix.

---

os/sdk-modifying-flatcar.md

See https://github.com/flatcar-linux/scripts/pull/80

Document caveat with SDK package URLs

---

README.md

The Kinvolk here is unnecessary.

Remove "Kinvolk" from README title

---

os/provisioning.md

provisioning: update path to flatcar

---

os/update-strategies.md

os: document update workaround

---

os/booting-with-libvirt.md

AppArmor step is necessary to run this doc on ubuntu
Backing_fmt parameter  is necessary

Add AppArmor step and backing_fmt parameter

---

.gitmodules
index.md

markdown lint and gitmodules URL update 

---

docs/_index.md
docs/clusters/management/update-conf.md

Closes https://github.com/kinvolk/Flatcar/issues/224

docs: define the update.conf

---

docs/container-runtimes/use-a-custom-docker-or-containerd-version.md

The CRI plugin needs to be enabled and the shim debug logs disabled,
to be aligned with the current state of Flatcar Stable. Also, it is
good to use the upstream Containerd socket location, while keeping a
symlink in place for the old Flatcar default.
```
cat ignition.yaml | ~/kinvolk/container-linux-config-transpiler/bin/ct > ignition.json
./flatcar_production_qemu.sh -i ignition.json
```

container-runtimes: Update settings for upstream containerd

---

docs/reference/developer-guides/sdk-modifying-flatcar.md

The arm64 target requires binary translation to be set up on the host system.
Document how to this can be set up, tested, and what the outcomes are.

reference/developer-guides/sdk-modifying-flatcar: Host system requirements for arm64

---

docs/reference/developer-guides/sdk-modifying-flatcar.md
docs/reference/developer-guides/sdk-tips-and-tricks.md

in this PR, we fix some wording / spelling issues - some light modifications have also been proposed.

developer-guides: minor fixes

---

docs/provisioning/cl-config/_index.md
docs/provisioning/cl-config/from-cloud-config.md

fix broken link to migrating-from-cloud-config page

---

docs/reference/developer-guides/sdk-disk-partitions.md
docs/setup/customization/network-config-with-networkd.md

The docs were referring to 404 page.
Signed-off-by: knrt10 <kautilya@kinvolk.io>

Fix ref links

---

docs/installing/cloud/azure.md

The Marketplace image has some quirks and the terminology and functions
are a bit difficult to understand when provisioning Flatcar instances.
Add more info on how to use the Marketplace image, what its plan values
are, and how instance userdata and user provisioning works.
Read https://www.flatcar-linux.org/docs/latest/installing/cloud/azure/ and see if the additions make sense.

azure: add more info on how to use Flatcar

---

docs/setup/releases/update-strategies.md

The existing way of disabling automatic updates with masking the
services was difficult when the user still wanted to do manual updates
because one needs to know that unmasking needs to be kept for the first
minutes after the reboot.
Document an easier and safer way that uses the update-engine config
file to disable automatic updates.
Tested the CLC snippet and that update-engine correctly does not find updates but is still running to be able to mark the partition as successful

update-strategies: document how to do manual updates

---

docs/migrating-from-coreos/update-from-container-linux.md
docs/setup/debug/manual-rollbacks.md
docs/setup/releases/switching-channels.md
update-to-flatcar.sh

- Improvements for the migration script
- Introduce the flatcar-update script from https://github.com/flatcar-linux/init/pull/53
- Reworked to have simpler instructions to follow and added some hints for things to check

Rework update and rollback docs

---

docs/setup/releases/update-strategies.md

The update post-install hook can be useful to run custom steps. Since it's not documented yet we do so here. The reboot window docs got moved closer to the reboot strategy docs.

Document OEM update hook and improve docs on reboot managers

---

docs/container-runtimes/switching-to-unified-cgroups.md
docs/installing/cloud/aws-ec2.md

Signed-off-by: Mathieu Tortuyaux <mathieu@kinvolk.io>
Related-to: https://github.com/flatcar-linux/Flatcar/issues/585

docs/container/cgroup: add AWS ECS agent as known issue

---

docs/provisioning/terraform/_index.md

The rerun of Ignition can keep the system's machine ID when stored as
kernel cmdline parameter.
Use a helper script that executes the required steps.

docs/provisioning/terraform: extend Ignition reprovisioning docs

---

docs/setup/releases/update-strategies.md

Fixes https://github.com/flatcar-linux/Flatcar/issues/259

Document update states

---

docs/setup/debug/collecting-crash-logs.md

The info was outdated because systemd-pstore.service didn't exist at
that time.
Give the new location for persistent file storage and document how the
files automatically get there.

debug/collecting-crash-logs: update pstore information

---

docs/setup/storage/adding-swap.md

Btrfs supports swap files since Linux 5.0 and we also have zram
available as alternative to writing pages to disk.

setup/storage/adding-swap: update docs for 2022

---

docs/setup/security/selinux.md

<hr>
Related-to: 
- https://github.com/flatcar-linux/Flatcar/issues/635
- https://github.com/flatcar-linux/mantle/pull/297

selinux: add current flannel limitation

---

docs/installing/_index.md

The existing docs were confusing and not really actionable to give an
interactive introduction experience.
Rework the docs to be hand-on with a local QEMU VM and a small CLC
config that runs an NGINX container.

installing: Rework Overview to be hand-on with QEMU and CLC

---

docs/installing/vms/libvirt.md

<hr>
Before that, it was required to edit the XML before defining the domain.

installing/libvirt: use --qemu-commandline flag

---

docs/installing/bare-metal/booting-with-ipxe.md
docs/installing/bare-metal/booting-with-iso.md
docs/installing/bare-metal/booting-with-pxe.md
docs/installing/bare-metal/installing-to-disk.md
docs/installing/cloud/aws-ec2.md
docs/installing/cloud/azure.md
docs/installing/cloud/equinix-metal.md
docs/installing/cloud/gcp.md
docs/installing/cloud/vmware.md
docs/installing/community-platforms/notes-for-distributors.md
docs/installing/vms/qemu.md
docs/setup/releases/verify-images.md

The Edge channel is not maintained anymore.

Remove references to Edge

---

docs/installing/cloud/equinix-metal.md

replace `packet` TF provider with `metal`.
Related to: https://github.com/flatcar-linux/flatcar-terraform/pull/11
Closes: https://github.com/flatcar-linux/Flatcar/issues/661

docs/equinix-metal: update terraform provider

---

docs/provisioning/ignition/specification.md

* add ignition3 spec
* move ignition3 section on top
* add current ignition 3 limitations

ignition: add ignition3 section

---

docs/provisioning/ignition/specification.md

ignition: add butane link

---

docs/container-runtimes/switching-to-unified-cgroups.md

this has been raised by the community on Matrix channel.

docs/container/cgroup: add OTEL segfaulft as known issue

---

docs/_index.md
docs/setup/customization/ACPI.md

<hr>
Related to:
- https://github.com/flatcar-linux/coreos-overlay/pull/1911
- https://github.com/flatcar-linux/Flatcar/issues/738

setup/customization: add acpid example

---

docs/_index.md
docs/setup/security/fips.md

<hr>
Related to:
* https://github.com/flatcar-linux/Flatcar/issues/537

security/fips: add fips guide

---

docs/reference/constants-and-ids.md

constant-and-id: broken link to disk layout

---

docs/provisioning/ignition/specification.md

docs/ignition: fix Ignition reuse semantics link

---

docs/reference/supply-chain.md

take->taken
ardware->hardware
👀 
👀

Fix minor typos in docs/reference/supply-chain.md

---

docs/installing/cloud/openstack.md
docs/installing/community-platforms/_index.md

* community-platforms: side node on community platforms
let's mention that the community platforms are not covered by the
automated tests.
* openstack: move to supported cloud

cloud: add openstack

---

docs/_index.md

<hr>
For some reasons, it was not originally present on the index page.

index: add openstack

---

docs/setup/systemd/timers.md

setup/systemd/timers: Migrate CLC to Butane

---

docs/_index.md
docs/setup/customization/using-nvidia.md

Initial docs for the NVIDIA drivers installation and customization process on Flatcar

Add docs for NVIDIA driver installation and customization
