flatcar/flatcar-docs

- ignition/boot-process.md
- ignition/what-is-ignition.md
- os/sdk-disk-partitions.md
If a machine was updated to Flatcar CL from CoreOS CL
it still has the old GRUB code which checks for
/boot/coreos/first_boot.
Document that this path is used for machines that
are migrated from CoreOS CL.
> Document coreos/first_boot for migrated machines

- os/booting-on-ec2.md
Also, instead of pointing to the site,
directly jump to the relevant section.
> Fix broken link to Provisioning site

- os/migrate-from-container-linux.md
The ignition.config.url migration is currently
needed but not in the next release.
The ignition.config.data migration is currently
not possible but can be done from the next
release on.
Fixes https://github.com/flatcar-linux/Flatcar/issues/45
> Document release dates in migration notes

- os/developer-guides.md
- os/sdk-modifying-flatcar.md
Before this patch, the URL was
https://docs.flatcar-linux.org/os/sdk-modifying-coreos/
> Update URL to sdk-modifying-flatcar

- os/booting-on-ec2.md
Now that AWS cloudformation has changed its URL scheme, we need to
adjust existing URLs to AWS cloudformation templates, like:
```
https://console.aws.amazon.com/cloudformation/home?region=eu-central-1#/stacks/new?stackName=flatcar-stable&templateURL=https://flatcar-prod-ami-import-eu-central-1.s3.amazonaws.com/dist/aws/flatcar-stable-hvm.template
```
> os: fix URLs to AWS cloudformation templates

- os/booting-on-vmware.md
- os/migrate-from-container-linux.md
The guestinfo.ignition.config.* variables did not work when used
as direct guestinfo variables but only via the ovfenv.
Document to use the old variables in the mean time and update the
date after which releases will be able to use the new generic variables.
> vmware: Use guestinfo.coreos.config.* until fix is released

- os/migrating-to-clcs.md
While cloud-config is still included in Flatcar Countainer Linux, we've never recommended using cloud-config.
> Fixed some historical representation

- os/sdk-modifying-flatcar.md
Now that mantle [v0.14.0](https://github.com/flatcar-linux/mantle/releases/tag/v0.14.0) was released, we need to update Flatcar docs, so it points to the latest cork version v0.14.0.
> os: update cork version to 0.14.0

- os/booting-on-ec2.md
This PR adds a paragraph on release retention for AWS AMIs to the AWS section of the Flatcar Container Linux documentation (inspired by our latest AMI garbage collection issue, https://github.com/flatcar-linux/Flatcar/issues/85).
Go to https://github.com/flatcar-linux/docs/blob/t-lo/ami-release-retention/os/booting-on-ec2.md, see 2nd paragraph.
Reviewed github's markdown rendering of the abovementioned document, second paragraph.
> booting-on-ec2: added paragraph on release retention

- os/sdk-tips-and-tricks.md
Unfortunately it is not enough to check for `coreos-base/hard-host-depends`.
We should also check for dependencies of `coreos-devel/sdk-depends`.
When checking for SDK dependencies, we should call `emerge` instead of `emerge-amd64-usr`. It is to be installed under the SDK environment, instead of in images.
> os: fix example of checking for SDK dependencies

- os/quickstart.md
Some links were pointing to coreos docs or blogs. This PR updates those.
> Update links for getting started and ignition

- os/update-from-container-linux.md
- update-to-flatcar.sh
The note to migrate was not having instructions how to do it and migration
was not part of the automatic script.
Add it in a way that it only runs if necessary and only uses a symlink so
that rolling back to the CoreOS partition will work.
Update a CoreOS CL VM to Flatcar CL with the script. If the `/var/lib/coreos-install` folder exists, a symlink should be created.
Tested that running the script multiple times works.
> update-from-container-linux: Create symlink for cloud-config user_data

- index.md
Some Ignition and CL Config Transpiler docs were linked or available
in the search but not part of the sitemap or navigation menu.
The list in Home also never mentioned Ignition nor how the CL Config,
the CL Config Transpiler and the CL Spec are related.
Add a short intro paragraph before listing the available docs.
> index: Add linked Ignition/CL Config docs to Home

- os/booting-on-vmware.md
- os/provisioning.md
- vmware: Update and expand the documentation    
Important basic information was missing, like the usage of ovftool
and how static IPs are configured.
The relation of Ignition and coreos-cloudinit is explained because
both use the same data source and Ignition has serveral limitations.
Depending on the use case, some important behavior was documented
such as which guestinfo variables result in what networkd setting
when coreos-cloudinit is used, or how custom templating should be
done with /run/metadata/coreos.
- os/provisioning: Mention the ct docker image
> vmware: Update and expand the documentation

- os/booting-with-libvirt.md
The Container Linux Config is shown as example but not how it can be
converted. Give more guidance about the relation of the first Ignition
example and the second where it is generated from the CL Config.
> os/booting-with-libvirt: Explain how to convert the CL Config

- os/installing-to-disk.md
Add missing options and update descriptions.
Already uses https://github.com/flatcar-linux/init/pull/18
Fixes https://github.com/flatcar-linux/Flatcar/issues/108
> os/installing-to-disk.md: Update flatcar-install options

- os/booting-on-ec2.md
Display the unofficial AWS China AMIs in a second table.
Only Stable amd64 releases are covered.
> os/booting-on-ec2: Add AWS China AMIs

- os/manual-rollbacks.md
- os/update-from-container-linux.md
Mention that "tries" needs to be set to 1 if the partition was not
successfully booted before but should be prioritized now.
Also add a note on the partition aliases and fix a link.
> os/manual-rollback: Set tries to 1 for an unsuccessful partition

- os/booting-on-vagrant.md
* include the box name to use
* name the added box "flatcar-alpha" to match examples
* the `vagrant status` shows 3 hosts, so make the Vagrantfile accomplish
as much
* the link to cluster information is still a CoreOS doc, not Flatcar
Linux yet
[ describe what reviewers need to do in order to validate this PR ]
[Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]
> vagrant: basic cluster information

- os/update-from-container-linux.md
- update-to-flatcar.sh
Any setting in /etc/coreos/update.conf was lost because the file
wasn't migrated to the new location.
Move it to the new location but keep a symlink. The SERVER parameter
won't be for Flatcar and was overwritten anyway and would be a duplicate
from the SERVER parameter in /usr/share/flatcar/update.conf.
Download a QEMU CoreOS CL image and the script to run it.
Copy the migration script to the VM and run it.
Check that the `/etc/flatcar/update.conf` file after rebooting contains `GROUP=stable`.
> update-from-container-linux: Migrate /etc/coreos/update.conf

- os/update-from-container-linux.md
- update-to-flatcar.sh
after running the update from coreos to flatcar, it failed as `update_engine_client` was requiring root access
> update_engine_client requires sudo access

- os/update-strategies.md
The documentation explained how to disable update-engine permanently
but the fact that updates don't work if update-engine is running only
shortly to update was not called out.
Explain that update-engine needs to run after the reboot, too, and show
how to check that the service can be disabled again safely.
> Note that update-engine needs to run after the reboot

- os/sdk-tips-and-tricks.md
For debugging purposes, we sometimes need to create an image that allows us to mount `/usr` as read-write.
> os: describe how to create an image for mounting /usr as read-write

- os/kernel-modules.md
overly pedantic shell cleanup and new path
a flatcar instance
walked through the examples.
> os: flatcar name and shell cleanup

- ignition/what-is-ignition.md
The `ignition` section of the Flatcar Container Linux documents currently references the incorrect version of the ignition specification - v3.x. v3.x is not supported at this time as Flatcar Container Linux ships `ignition` binary v0.3x, which supports v2.x of the spec.
> what-is-ignition.md: link to v2.x spec examples instead of v3.x

- os/booting-on-vmware.md
- os/migrate-from-container-linux.md
Both coreos.config.* and ignition.config.* variables are supported
but we recommend to use the more generic Ignition name even for
cloud config data because it uses the same data source as Ignition.
> os/booting-on-vmware.md: Default to ignition.config.* variables

- os/torcx-overview.md
Some URLs in the torcx documentation still pointed to CoreOS. This PR updates the respective markdown file to reference Flatcar documentation and github repos.
Use the "rich diff" in the "files changed" tab to preview the markdown rendering.
> os/torcx-overview.md: update links to point to Flatcar docs

- os/sdk-modifying-flatcar.md
The default branches to be checked out will be the Alpha development
branches with the latest Alpha SDK.
See https://github.com/flatcar-linux/manifest/pull/14
The release branch of the manifest has changed from flatcar-build-x.y.z
to flatcar-CHANNEL-x.y.z which is updated here as well.
As replacement mechanism for the current CHANNEL-master.xml files
a new maintenance.xml is proposed that is part of the release tag/
branch of the manifest repository (not yet released).
> os/sdk-modifying-flatcar.md: Document cork create usage

- os/sdk-modifying-flatcar.md
The nightly builds are done per branch. A branch can be the development branch or a maintenance branch of a major version.
> os/sdk-modifying-flatcar.md: Document new nightly naming scheme

- os/sdk-modifying-flatcar.md
A newer cork release which allows to verify that git tags are checked
out correctly, set the correct SDK version if passed as parameter, and
download developer SDKs.
Test that download and verification works
> os/sdk-modifying-flatcar: Use new cork release

- os/sdk-modifying-flatcar.md
The correct SDK binary package URL saves a lot of time and helps to
avoid any build problems with circular dependencies.
See https://github.com/flatcar-linux/scripts/pull/86
> os/sdk-modifying-flatcar.md: Document how to select the nightly SDK

- os/sdk-modifying-flatcar.md
The names were not explicitly mentioned because the transition to the
new branch structure wasn't completed. We have now settled for `main`
as development branch but there is no new Edge development branch yet
which needs to be added here later.
> os/sdk-modifying-flatcar.md: Call out name of development branch

- index.md
- os/cluster-architectures.md
- os/configuring-date-and-timezone.md
- os/customizing-docker.md
- os/getting-started-with-docker.md
- os/installing-to-disk.md
- os/notes-for-distributors.md
- os/quickstart.md
- os/registry-authentication.md
- os/root-filesystem-placement.md
- os/update-strategies.md
Closes: #34
looks through for newer links or the current place the docs are hosted for Flatcar.
View the docs.
Walked through the location of the link, and ensure the new location is up-to-date and relevant.
> *: point docs to the Flatcar or current links

- os/booting-on-google-compute-engine.md
Our GCE docs currently include a section about deploying cloud images to GCE that doesn't work because we don't have a public project (yet). Comment it out for now.
We will have a public project soon, we can remove the comments then and move the customization section to the bottom.
Check out the preview docs
> GCE: Comment out the section about public cloud images

- os/getting-started-with-docker.md
While starting containers through systemd services is recommended,
document how to run Docker on boot as prerequisite to use Docker's
support for (re-)starting containers.
See https://github.com/flatcar-linux/Flatcar/issues/134
> os/getting-started-with-docker.md: How to start Docker on boot

- os/sdk-modifying-flatcar.md
Tested that links work:
https://github.com/flatcar-linux/mantle/releases/download/v0.15.1/cork-0.15.1-amd64
https://github.com/flatcar-linux/mantle/releases/download/v0.15.1/cork-0.15.1-amd64.sig
> os/sdk-modifying-flatcar.md: Update cork version for new subkey

- docs/quickstart/_index.md
Ignition docs link still pointed to coreos; updating to point to kinvolk.io/docs
> quickstart: link ignition docs coreos => kinvolk

- docs/clusters/management/update-conf.md
The new optional variable MACHINE_ALIAS is documented, mainly to be
used in conjunction with a private update server.
> update-conf.md: Document MACHINE_ALIAS variable

- docs/reference/developer-guides/sdk-disk-partitions.md
The OEM partition is not mounted read-only but can be written to.
> sdk-disk-partitions.md: Correct OEM partition mount description

- docs/bare-metal/installing-to-disk.md
- docs/bare-metal/notes-for-distributors.md
- docs/cloud-providers/booting-on-virtualbox.md
- docs/cloud-providers/booting-on-vmware.md
- docs/clusters/creation/cluster-discovery.md
- docs/clusters/customization/adding-users.md
- docs/clusters/customization/using-environment-variables-in-systemd-units.md
- docs/clusters/management/registry-authentication.md
- docs/clusters/securing/adding-certificate-authorities.md
- docs/community-platforms/booting-on-exoscale.md
- docs/community-platforms/booting-on-rackspace.md
- docs/community-platforms/booting-on-vultr.md
- docs/container-runtimes/generate-self-signed-certificates.md
- docs/contribute/docs.md
- docs/ignition/_index.md
- docs/ignition/metadata.md
- docs/quickstart/_index.md
- docs/reference/developer-guides/_index.md
- docs/reference/developer-guides/sdk-tips-and-tricks.md
- docs/reference/migrating-to-clcs/_index.md
- docs/reference/migrating-to-clcs/provisioning.md
External links containing markdown extension were broken during refactoring done at ee10233 (#124).
N/A
- Ensured the changed links are now working
- All changed links in ee10233 that are matching `\w+:\/\/.+\.md` were reverted
> Fix missing markdown extension in external links

- docs/_index.md
- docs/container-runtimes/switching-from-docker-to-containerd-for-kubernetes.md
To be used with Kubernetes.
Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>
> docs/container-runtimes: add containerd configuration examples

- docs/reference/developer-guides/sdk-modifying-flatcar.md
Update the cork version to 0.15.2, to fix recent bugs around `repo init` commands.
Also change the github org name to `kinvolk`.
Also remove unnecessary commands for receiving a gpg key, because the cork binary file is now signed with the image build signing key.
> docs: update cork to 0.15.2, remove gpg key

- docs/cloud-providers/booting-on-virtualbox.md
Branch names of provisioning scripts were pointing to `.../master/...` instead of `.../flatcar-master/...`. The `master` branch is abandoned and contains outdated scripts with CoreOS URIs.
> cloud-providers/booting-on-virtualbox: fix branch names

- docs/_index.md
- docs/container-runtimes/customizing-docker.md
- docs/container-runtimes/use-a-custom-docker-or-containerd-version.md
- Add new docs on deploying a custom Docker version through Ignition
Even though Torcx exists for some time already, it's not really
accessible and has several flaws. Therefore, users tend to prefer to
provisioning custom binaries through Ignition but there are no docs
yet about this.
Document how to replicate the Docker setup Flatcar has by writing new
files to /etc and /opt/bin as a starting point for users to do their
customizations, like just downloading containerd or additional tools.
- customizing-docker: Show how to use a custom containerd configuration
- docs/container-runtimes/customizing-docker.md: Capital D for Docker
Save the config file and convert it: `cat config.yaml | container-linux-config-transpiler/bin/ct > config.json`
Start a VM: `./flatcar_production_qemu.sh -i …
> Using a custom Docker version

- docs/container-runtimes/use-a-custom-docker-or-containerd-version.md
When writing the docs I considered using the default containerd socket
but then switched back to what we use in Flatcar. However, I forgot to
do it in the dockerd argument.
I reran the test and verified that Docker runs as expected and uses the correct socket path.
> use-a-custom-docker-or-containerd-version.md: Fix inconsistent path

- docs/_index.md
- docs/cloud-providers/booting-on-hetzner.md
- docs/cloud-providers/booting-on-packet.md
- docs/cloud-providers/booting-with-libvirt.md
- docs/clusters/creation/cluster-architectures.md
- docs/community-platforms/_index.md
- docs/quickstart/_index.md
- docs/reference/integrations.md
- docs/terraform/_index.md
A generic document describes how Terraform is used together with
Flatcar and Ignition. It covers the general principle. how to
generate the Ignition config and how to handle User Data changes.
An extra sections goes into the details of storing the User Data in
a remote location and rerunning Ignition in a safe way to circumvent
node recreation.
The provider-specific instructions for Terraform with Equinix Metal,
libvirt, and Hetzner are added to the cloud provider docs.
> Document Terraform usage

- docs/cloud-providers/booting-on-google-compute-engine.md
We had commented out the instructions for deploying GCP instances,
because they were using a non existant "flatcar-cloud" project. We now
have a "kinvolk-public" project, where we publish GCP images and we can
now publish instructions on how to install these images.
> Make the GCP kinvolk-public project known

- docs/cloud-providers/using-google-cloud-launcher.md
The image path was wrong, so images were not showing. While fixing this,
also added a few more sentences, so that the text flows better. And
removed some whitespace that's not needed due to our CSS.
> Fix images for the GCP Marketplace launcher page

- docs/container-runtimes/switching-from-docker-to-containerd-for-kubernetes.md
The latest Stable release does not need the workaround for Kubernetes
and containerd anymore.
> docs/container-runtimes: Remove workaround for CRI plugin

- docs/provisioning/terraform/_index.md
The original repository was part of a talk presentation.
Now that we will add more examples, the repository was moved under
kinvolk/.
> provisioning/terraform: Use new repo location

- docs/setup/storage/iscsi.md
With the iscsi update, the systemd service that controls the
other services is `iscsi`
Signed-off-by: Sayan Chowdhury <sayan@kinvolk.io>
> Update the iscsi service name to reflect changes from update

- docs/container-runtimes/switching-from-docker-to-containerd-for-kubernetes.md
The default socket location was changed (in a backwards-compatible way
through a symlink on the old location) and the section about using the
upstream defaults was confusing because it also involved breaking
Docker which should be solved by disabling the Docker service and
socket, not through a broken configuration.
> container-runtimes: Update section about using containerd for K8s

- docs/installing/cloud/digitalocean.md
- docs/installing/cloud/hetzner.md
The instructions to run a droplet assumed a public image to be
available which isn't.
Update the instructions on how to create a custom image on the command
line or in Terraform.
Tested in https://github.com/kinvolk/flatcar-terraform/pull/6
> installing/cloud/digitalocean: Update and extend instructions

- docs/installing/bare-metal/booting-with-pxe.md
This was missed from my link-fix effort because it was hidden inside HTML code.
> Fix link to notes-for-distributors

- docs/provisioning/config-transpiler/getting-started.md
The example file was changed to a different directory but the link hadn't been fixed.
Fixes: kinvolk/Flatcar#344
Tested by running a local website and verifying that the link is now correct.
> Fix path to the CL Config example file

- docs/installing/cloud/vmware.md
Disabling the autologin setting is not really a safety measure because
with console access it's possible to set it again from the GRUB menu
but it's still something that user may want or even have to do to meet
certain requirements.
> vmware: document how to disable autologin

- docs/provisioning/ignition/network-configuration.md
The docs for static IP settings during Ignition run specify two alternative formats for the IP configuration passed on the kernel command line, but as written, this wasn't necessarily obvious on first reading. It appears as though the initial author had intended to insert subheadings but that they had gotten dropped. This commit adds headings, which clarify the meaning and make it easy to recognize the two formats and their differences on a first reading.
Read the docs!
Prosaic alterations were tested using GitHub's markdown renderer, both before and after committing. HTML/CSS output from GitHub was subsequently processed using Firefox to render a final result. This result was transmitted to an IPS panel display. Emissions from the display were recorded using an organic photo-optical …
> Fix kinvolk/Flatcar#351: Add headings for clarity

- docs/installing/community-platforms/notes-for-distributors.md
The original CoreOS blog post on the introduction of Ignition (and the rest of the blog) seems to be gone now. Update this link to point to a copy of the post on Todd Pigram's blog.
Read the docs!
Examined change carefully, and tried opening the link to be sure it was pasted correctly. :)
> Fix dead link

- docs/reference/developer-guides/_index.md
- docs/reference/developer-guides/sdk-bootstrapping.md
- docs/reference/developer-guides/sdk-modifying-flatcar.md
- docs/reference/developer-guides/sdk-tips-and-tricks.md
This PR improves the "modifying Flatcar" docs; removong some edge
case details (like nightly build SDKs) and adding HOWTOs for updating
or adding packages, and for modifying the kernel.
Furthermore, a new high-level document on the SDK bootstrapping process
is added.
> SDK: improve image building doc, add SDK bootstrapping

- docs/reference/developer-guides/_index.md
- docs/reference/developer-guides/sdk-modifying-flatcar.md
This PR fixes a missing `</code>` tag and drops the "Developer" from the "Guide to building customised Flatcar images" title, since that document is already in the "Developer" section of the docs, removing some redundancy redundancy.
> developer-guides: syntax fixes, drop "developer" from heading

- docs/reference/developer-guides/sdk-modifying-flatcar.md
* QEmu -> QEMU
* Remove extra backtick
> sdk-modifying-flatcar.md: fix two typos

- docs/reference/developer-guides/sdk-modifying-flatcar.md
This only worked for me when `--autounmask=y` was added too.
> sdk-modifying-flatcar.md: expand autounmask instruction

- docs/installing/bare-metal/booting-with-ipxe.md
- docs/installing/bare-metal/booting-with-pxe.md
I found two broken links in the docs.
AFAIK, There's no other broken links (I tried to find same types of broken links using scripts)
- https://kinvolk.io/docs/flatcar-container-linux/latest/installing/bare-metal/booting-with-ipxe/#adding-a-custom-oem
- https://kinvolk.io/docs/flatcar-container-linux/latest/installing/bare-metal/booting-with-pxe/#installation
Rebuilding pages may fix the problems.
I don't know how to build this, so I couldn't check whether this pr successfully fix the problems.
> Fix broken links

- docs/installing/cloud/azure.md
This documents the Flatcar Pro marketplace images and how to query them
from the CLI. Currently the latest release does not support the GPU
drivers and an old version has to be used, this is documented as well.
> Add docs for Flatcar Pro on Azure

- docs/reference/developer-guides/sdk-modifying-flatcar.md
since we don't ship qemu in the SDK with `slirp`, user
needs to use its own qemu to use user networking
Signed-off-by: Mathieu Tortuyaux <mathieu@kinvolk.io>
closes https://github.com/kinvolk/Flatcar/issues/420
> flatcar/developer-guide: exit SDK before running script

- docs/reference/developer-guides/_index.md
The previous link leads to a document that just redirects to the Fedora CoreOS docs. Fix the link to point to the flatcar-master branch.
> Fix link to kola docs

- docs/reference/developer-guides/sdk-modifying-flatcar.md
This was causing trouble for me when I was trying to use `cork` inside
`/tmp`.
Suggested-by: Jeremi Piotrowski <jpiotrowski@microsoft.com>
Suggested-by: Thilo Fromm <thilo@kinvolk.io>
Signed-off-by: Chris Tarazi <tarazichris@gmail.com>
> docs: Add note for SDK directories mounted with `nodev`

- docs/provisioning/cl-config/_index.md
`etcd:` does not make it through the config transpiler, and the ignition json ends up empty.
Assigning an empty objects resolves that.
> provisioning: fix example of launching etcd

- docs/container-runtimes/switching-to-unified-cgroups.md
Add a page under `container runtimes` that explains the details of the cgroupv2 migration and impact.
> cgroup v2 docs

- docs/container-runtimes/switching-to-unified-cgroups.md
The Alpha version to be released containing the cgroups v2 changes is `2969.0.0`. This commit updates the placeholder version we added earlier.
We will merge after we have released the Alpha version.
> docs: Fix the Flatcar Container Linux version updating cgroupsv2

- docs/container-runtimes/switching-to-unified-cgroups.md
The previous one breaks containerd in kubernetes unless one is very careful.
Add a fuller snippet so that copy-pasting is safe.
Related to https://github.com/kinvolk/coreos-overlay/pull/1214
> unified-cgroups: Update containerd config snippet

- docs/reference/developer-guides/kernel-modules.md
The old method doesn't work, and because Flatcar doesn't compile gpg with ssl support,
none of the other gpg servers will work. Instead fetch and import the key using curl.
> developer-guides: kernel-module: fix fetching of gpg signing key

- docs/reference/developer-guides/sdk-modifying-flatcar.md
Update the cork URLs to point to the updated ones.
> docs: Update cork to point to 0.16.0 artifacts

- docs/installing/community-platforms/notes-for-distributors.md
- docs/reference/developer-guides/kernel-modules.md
- docs/reference/developer-guides/sdk-modifying-flatcar.md
The old website has redirects in place for many parts but not for all,
and thus, the image signing key was outdated.
Use the right URL which users will also find on the website.
> Use correct image signing key URL

- docs/reference/developer-guides/sdk-modifying-flatcar.md
The default parameter is computed based on the board: for amd64 it's
qemu but for arm64 it's qemu_uefi. For users reading the docs it may
result in generating the wrong image type for arm64 which means that
the firmware files are not copied to the target directory and have to
be added manually.
Do not hardcode the format value in the docs but omit the parameter so
that it will choose the right default automatically.
> developer-guides/sdk-modifying-flatcar.md: use dynamic format default

- docs/provisioning/ignition/boot-process.md
Running Ignition on an already booted root filesystem has many traps.
One of them is that systemd service presets are not reevaluated,
resulting in all new supposed-to-be-enabled services being disabled by
default.
Document how to invalidate the machine-id file so that systemd
reevaluates the service presets.
Booted a qemu image, then created the `first_boot` flag file and booted it again with an Ignition config set. The service in the Ignition config does not get enabled unless one also did invalidate the machine-id file.
> provisioning/ignition/boot-process: document how to simulate first boot

- docs/reference/developer-guides/sdk-modifying-flatcar.md
Multiple changes happened in October 2021:
* the new default URL in cork (mirror.release.flatcar-linux.net/sdk) only has releases that happened after
October 2021, so update the SDK versions used in examples to recent ones.
* the website is moving from kinvolk.io to flatcar-linux.org so update url to releases.json (old url is not a
redirect and does not get updated) and to GPG key (old url works). The GPG output also needed updating.
* cork 0.17.0 has updated urls so reference that.
Follow the instructions.
> developer-guides: Update urls/cork/releases used in SDK example

- docs/reference/developer-guides/sdk-tips-and-tricks.md
The default binhost URL is for releases, the nightly binary packages
get published on the bucket only which needs to be specified.
See https://github.com/flatcar-linux/scripts/pull/171
> Set binhost for nightly package store

- docs/container-runtimes/customizing-docker.md
The existing /usr/bin/containerd torcx wrapper already takes care of
using the right binaries. The torcx path in the customization
instructions can be avoided which helps to make this more future-proof
when torcx is not used. Also, the default config is under /etc and does
not need to be specified (the env var is custom to torcx, too).
Do not set up the env var nor specify the config path, and stop
hardcoding the torcx binary path.
I created a config in `/etc` and checked that it gets taken up and that the containerd service works.
> container-runtimes: simpler and future-proof containerd customization

- docs/setup/storage/adding-swap.md
Container Linux config sample with sections for disks, filesystems and the systemd unit to mount swap.
Create an ignition file including the transpiled content from the example.
Start a VM with an additional disk that will be mounted as /dev/sdb on first boot.
This has been tested on GCE using this script to start VMs:
```bash
#!/bin/bash
VMNAME=test-123
ZONE=us-central1-a
PROJECT=myproject
gcloud compute instances create "$VMNAME" --project="$PROJECT" \
--zone "$ZONE" --machine-type e2-standard-2 \
--network-interface=network-tier=PREMIUM,subnet="$PROJECT"vpc-01 \
--create-disk=auto-delete=yes,boot=yes,device-name="$VMNAME"-boot,image-project=kinvolk-public,image-family=flatcar-stable,mode=rw,size=100,type=projects/"$PROJECT"/zones/"$ZONE"/diskTypes/pd-standard \ …
```
> Add example for whole disk as swap

- docs/installing/cloud/vmware.md
- docs/provisioning/config-transpiler/dynamic-data.md
The custom platform guide talks about using a drop-in unit but when a
non-OEM image is used, it doesn't have the service file at all.
The example used there and in the VMware docs was also lacking some
safety net for temporary malfunctioning metadata servers.
Instruct that the service file should be created instead of using a
drop-in (For existing OEM service files it will work as well to create
the service file under `/etc` which has a higher priority).
Also add some more options to make the oneshot unit more robust.
Fixes https://github.com/flatcar-linux/Flatcar/issues/573
> config-transpiler/dynamic-data.md: correct custom platform guide

- docs/installing/customizing-the-image/_index.md
- docs/installing/customizing-the-image/customize-the-image.md
- docs/reference/developer-guides/_index.md
- docs/reference/developer-guides/sdk-modifying-flatcar.md
- While users often had the need to customize the image, we had no docs
to point to. Also, there are many traps when people try to customize
by booting an image and we have to warn users about them.    
Add a new document that captures the tribal knowledge of image
preparation and guides the users to select the appropriate method
without running into the traps.
- Rename image building guide  
The image building guide we maintain is for building from source in
contrast to a future guide of customizing a Flatcar image by modifying
it directly.
Rename the image building guide to be more clear about what it does,
in order to add a future guide for customizing Flatcar images.
> Add guide for image customization

- docs/_index.md
- docs/reference/developer-guides/_index.md
- docs/reference/developer-guides/sdk-bootstrapping.md
- docs/reference/developer-guides/sdk-building-production-images.md
- docs/reference/developer-guides/sdk-modifying-flatcar.md
- docs/reference/developer-guides/sdk-tips-and-tricks.md
This PR updates the developer reference documentation to cover the SDK container.
It also repurposes the "building production images" document to discuss containerised builds and CI automation.
> reference/SDK: rework SDK docs,cover container SDK

- docs/provisioning/ignition/boot-process.md
When reruning Ignition, the machine ID file should be removed to
trigger systemd preset evaluation but at the same time a user may want
to use the same machine ID as before.
Document how to preserve the current machine ID by storing it in the
GRUB kernel command line.
Manually tested that the same machine ID gets used after `sudo rm -rf --one-file-system --no-preserve-root /`
> provisioning/ignition/boot-process: tell how to preserve the machine ID

- docs/setup/releases/update-conf.md
- docs/setup/releases/update-strategies.md
- setup/releases/update-conf: add more info on how to use the parameters
- setup/releases/update-strategies: document the flatcar-update tool    
When automatic updates are disabled and the update should be done
manually it helps to still use the flatcar-update tool as it handles
the disabling of updates again at the right time.
Document it as alternative to doing all steps manually.
> Add more info on the update.conf file and manual updates

- docs/installing/cloud/vmware.md
- docs/reference/developer-guides/sdk-disk-partitions.md
- docs/setup/customization/other-settings.md
- docs/setup/releases/update-strategies.md
- docs/setup/security/disabling-smt.md
While we support passing ext4 as config entry for the OEM filesystem in
Ignition, this will be ignored since btrfs is used.
Update the docs to avoid any confusion.
While on it also fix the USR partition filesystem which is ext2, not  
ext4.
> Use real OEM filesystem when specifying it

- docs/reference/developer-guides/sdk-modifying-flatcar.md
The SDK / OS image build documentation lacked a step to install the updated `coreos-base/coreos` meta-package so newly added packages never made it into the image. Found while working on my FOSDEM devroom talk.
> SDK / OS image: fix documentation (update coreos-base)

- docs/setup/storage/adding-swap.md
Service units as default dependencies to `sysinit.target`, this can
create a cycle since `create-swap.service` is required by
`var-vm-swapfile1.swap` and this is required by `swap.target` which is
required by `sysinit.target`.
> adding-swap: break dependencies cycle

- create_cgroupv1_ami.sh
- docs/container-runtimes/switching-to-unified-cgroups.md
- docs/installing/customizing-the-image/customize-the-image.md
The script helps users to upload cgroup v1 AMIs and also serves as an
example on how image customization is done.
Script does what it should, tested with a qemu OEM image
> Add create_cgroupv1_ami.sh script

- docs/setup/systemd/getting-started.md
The example used some pre commands that can be shortened. It also
didn't specify to restart the service.
none
> setup/systemd/getting-started: update Docker container example

- docs/provisioning/ignition/_index.md
- docs/provisioning/ignition/specification.md
The Ignition specification was missing while we had the CLC
specification. This meant going to the GitHub repo docs folder to find
it.
Directly provide the config spec in our docs. Currently Flatcar Stable
supports only spec version 2.3.0.
Need to render it and check for syntax errors
None
> provisioning/ignition: add specifictation

- docs/installing/vms/libvirt.md
- docs/provisioning/cl-config/_index.md
- docs/provisioning/config-transpiler/getting-started.md
We moved our ct container to ghcr.io - this change updates the documentation accordingly (except for `docs/installing/_index.md` which is updated in https://github.com/flatcar-linux/flatcar-docs/pull/219).
> Update ct container references to use ghcr

- docs/installing/cloud/equinix-metal.md
<hr>
Terraform examples are still relying on Packet provider: https://github.com/flatcar-linux/Flatcar/issues/661
I was thinking about adding example of how to use ignition to wrap flatcar-install script and user config in case of iPXE booting but not sure it's relevant...
> installing/equinix-metal: update links

- docs/installing/bare-metal/booting-with-ipxe.md
- docs/installing/bare-metal/booting-with-pxe.md
- docs/installing/bare-metal/installing-to-disk.md
- docs/installing/cloud/aws-ec2.md
- docs/installing/cloud/azure.md
- docs/installing/cloud/digitalocean.md
- docs/installing/cloud/equinix-metal.md
- docs/installing/cloud/gcp.md
- docs/installing/cloud/vmware.md
- docs/installing/community-platforms/openstack.md
For users the special "etcd" directive is not really helpful as first
example.
Use a systemd unit to run an NGINX Docker container as example for the
platform instructions.
> installing: replace etcd example by NGINX container through systemd

- docs/installing/_index.md
The link targets were missing and thus the link didn't get rendered.
Add/correct the target.
Checked local rendering
> installing/_index: add missing links

- docs/installing/_index.md
Fix the URL and filename of the flatcar_production_qemu.sh file. The incorrect URL has a _image postfix and doesn't exist on the server. The guide later uses the correct filename for the script, which led me to think that the download instructions were wrong.
Did a wget with the correct URL.
> docs/installing/_index: Fix flatcar_production_qemu.sh URL

- docs/container-runtimes/use-a-custom-docker-or-containerd-version.md
When the PATH was not set, Torcx's binaries would have still been used.
Disable the Torcx generator to prevent it from running.
> custom-docker: also disable Torcx to prevent using it

- docs/installing/vms/libvirt.md
> installing/libvirt: fix indent and missing '='

- docs/_index.md
- docs/container-runtimes/use-a-custom-docker-or-containerd-version.md
- docs/provisioning/sysext/_index.md
With Alpha 3185.0.0 we have the basics for users to start extending the
base OS with systemd-sysext. The replacement of custom Torcx images is
already possible and we also provide a helper to create sysext images
from the Docker release binaries.
the resulting images work
> Add systemd-sysext docs for custom extensions

- docs/installing/cloud/azure.md
Following feedback received from a very considerate reader, this PR fixes a number of issues with the `chrony` example configuration. Also, terminology and description around rtc and PTP clock sources were updated following the feedback.
> docs/installing/cloud/azure.md: fixed chrony config and terminology.

- docs/container-runtimes/switching-to-unified-cgroups.md
The bind-mount workaround is not the recommended state the system
should be in when using cgroupv1 because it has some negative effects.
Always set the bootloader kernel cmdline explicitly as well in the
snippet example to make sure that the workaround is only needed on the
first boot. Also document one known issue.
> switching-to-unified-cgroups: also set the bootloader kernel cmdline

- docs/installing/bare-metal/raspberry-pi.md
Add documentation on how to run Flatcar Container Linux on Raspberry PI
Added the file in the path `Installing > Bare Metal > Running on Raspberry Pi 4`
> docs: Add the documentation for running FCL on RPi

- docs/installing/bare-metal/installing-to-disk.md
- docs/setup/releases/switching-channels.md
- docs/setup/releases/update-strategies.md
The docs were a bit sparse about channels and the group entry in
update.conf, specially for the yearly LTS streams. The docs also didn't
talk about setting up an own Nebraska update server for controlling the
update rollout.
Extend the docs about the different channels and how they are
configured in update-engine, with additional info for the LTS streams.
Also recommend the usage of Nebraska and tell shortly how it's used
while pointing to the Nebraska standalone docs for more.
Fixes https://github.com/flatcar-linux/Flatcar/issues/46
> Add more docs about channels and the update server

- docs/setup/releases/switching-channels.md
The LTS channel docs didn't talk about using an Nebraska instance to
manage the Flatar LTS deployment. Also, a few sentences weren't
explicit enough.
Call out how Nebraska can be used instead of managing the GROUP entries
on the individual machines to control the rollout of a new major LTS
release stream. Also reword a few sentences to be more explicit and fix
a markdown syntax error.
> setup/releases/switching-channels.md: Improve docs for LTS channel

- docs/reference/developer-guides/sdk-modifying-flatcar.md
The explicit alpine arm64 image was used as test but with the new arch
option for Docker/Podman we can use this instead as alternative. Also,
with Podman we have to use the full image name or Podman asks which
registry to use.
> sdk-modifying-flatcar: Document new Docker arch flag and use full name

- docs/installing/cloud/aws-ec2.md
- docs/installing/community-platforms/rackspace.md
- docs/setup/storage/mounting-storage.md
The kernel assigns /dev/sdX nodes by the order the disk is discovered
which can be different each boot. When a path such as /dev/sda is used
for mounting, this can result in a mismatch after reboot.
The better way is to always match the disk by the content that is
expected through the paths under /dev/disk/by-label/ and make sure the
labels get created on the first boot. An alternative when this is not
possible is to use /dev/disk/by-path/.
> Document how to avoid mismatching mounts after reboot

- docs/container-runtimes/use-a-custom-docker-or-containerd-version.md
- docs/provisioning/sysext/_index.md
The instructions used symlinks to /dev/null to "mask" a sysext image
but it turns out that only empty directories work as of now and the
symlink approach actually doesn't which was an oversight in testing.
> Correct sysext masking docs

- docs/installing/cloud/equinix-metal.md
- docs/installing/cloud/vmware.md
- docs/setup/customization/other-settings.md
- docs/setup/security/hardening-guide.md
Since the group gets provided by nss-altfiles on runtime from the
read-only user DB in /usr, the groups docker and wheel can't be changed
to remove the core user.
The solution to restrict access is to disable the core user, restrict
sudo access, or to
change the permissions of the Docker socket.
The rkt section can be deleted as rkt is gone.
> hardening-guide: Document how to disable the core user

- docs/setup/storage/adding-disk-space.md
AWS EBS volumes made after 2016 can be resized. This adds a link to the documentation on how to do so.
Set up an AWS EC2 instance with an EBS volume and run the command `aws ec2 modify-volume --volume-id <ID> --size <NEW SIZE>`. You can verify this on the machine by running `lsblk`.
I used Terraform to set this up, so I simply changed the volume size, reapplied, and went to the machine and ran `lsblk`.
- [] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)
> setup/storage/adding-disk-space: update description and link for AWS

- docs/setup/security/fips.md
OpenSSL FIPS proposal has been validated.
See also: https://www.openssl.org/blog/blog/2022/08/24/FIPS-validation-certificate-issued/
> security/fips: add OpenSSL FIPS validation

- docs/setup/customization/ACPI.md
Qemu-guest-agent is used in some of the same contexts as acpid, so mention how this works, and the option needed for openstack instances.
> customization/acpi: add section about qemu-guest-agent

- docs/reference/developer-guides/sdk-disk-partitions.md
The prior chromium site complains that the link is outdated and should be updated.
Open the new URL :-)
Checked the new URL to be working and that it show the expected content. 
I suppose the following template items would not be relevant for this kind of change, right?
> Update link to chromium disk layout

- docs/installing/cloud/aws-ec2.md
- docs/installing/cloud/azure.md
- docs/installing/cloud/digitalocean.md
- docs/installing/cloud/equinix-metal.md
- docs/installing/cloud/hetzner.md
The link to the repo was missing for Hetzner.
Like with the other Terraform cloud provider docs, link to the repo at the end.
> hetzner: Add link to GitHub repo

- docs/installing/_index.md
- docs/installing/bare-metal/booting-with-ipxe.md
- docs/installing/bare-metal/booting-with-pxe.md
- docs/installing/bare-metal/installing-to-disk.md
- docs/installing/cloud/aws-ec2.md
- docs/installing/cloud/azure.md
- docs/installing/cloud/digitalocean.md
- docs/installing/cloud/equinix-metal.md
- docs/installing/cloud/gcp.md
- docs/installing/cloud/openstack.md
- docs/installing/cloud/vmware.md
The default Docker log backend is using json files and for long running processes they could easily fill up the disk.
Use the journald logging backend to benefit from truncating. The "none" backend is also an option but it makes "docker log ID" fail. The drawback with the journald backend is that it duplicates the system wide entries because we already have them from the systemd unit stdout.
none
> nginx example: Use journald logging backend

- docs/contribute/_index.md
- docs/contribute/docs.md
Fix a broke link https://www.flatcar.org/docs/latest/contribute/STYLE, which should be actually https://www.flatcar.org/docs/latest/contribute/docs.
Discussed during the Linux community meeting.
> docs: fix a broken link to the style guide

- docs/reference/developer-guides/sdk-modifying-flatcar.md
The old link still works, but points to a page that doesn't have the SDK images.
> sdk-modifying-flatcar: update org name in container registry link

- docs/provisioning/ignition/_index.md
- docs/provisioning/ignition/boot-process.md
- docs/provisioning/terraform/_index.md
- docs/setup/releases/update-strategies.md
- Document flatcar-reset tool
- Document the /etc overlay cleanup logic and how to opt-out
Later I'll also look into updating the Terraform example setup to make use of flatcar-reset.
> Document Alpha 3535.0.0 changes for /etc overlay and flatcar-reset

- docs/provisioning/terraform/_index.md
- docs/reference/developer-guides/sdk-disk-partitions.md
- docs/setup/releases/update-strategies.md
- Mention terraform setup for flatcar-reset
The updated terraform setup in
https://github.com/flatcar/flatcar-terraform/pull/14 uses flatcar-reset
to preserve wanted data in the rootfs.
- Document how to list the contents of the underlying real /etc
- Hint at flatcar-reset tool for removing rootfs state
> Improve docs for flatcar-reset and the overlay

- docs/setup/releases/update-strategies.md
- update-stategies: Rename the title to refect the content
- update-stategies: Recommend to use flatcar-pxe-update-engine
The flatcar-pxe-update-engine project provides an update_engine
replacement for PXE in-memory boots that don't install to disk.
I haven't tried flatcar-pxe-update-engine myself but it is actively maintained.
> update-stategies: Recommend to use flatcar-pxe-update-engine

- docs/setup/systemd/getting-started.md
As discussed in https://github.com/flatcar/Flatcar/issues/65 the single path that systemd supports for shutdown hooks does not work for read- only images but we can use regular units to run custom shutdown actions. Document one way to do it (there are many other ways how to express this with systemd units).
Tested this by enabling the unit and rebooting/powering off to check that the marker file appears and `bye` is in the journal.
> systemd: Document how to add custom shutdown actions

- docs/_index.md
- docs/container-runtimes/registry-authentication.md
- docs/provisioning/config-transpiler/examples.md
The Butane docs section didn't have the examples like CLC and since registry-authentication.md linked to them, they were migrated.
Copied the examples into `butane` to check for warnings
Note that we can also try to cover Flatcar in https://coreos.github.io/butane/examples/
> Butane: Migrate basic examples

- docs/provisioning/sysext/_index.md
The recommended way to start sysext-shipped units is to use Upholds. Flatcar has a workaround for supporting target-wants symlinks but we may drop it in the future once upstream has support for reloading the units from disk to make Upholds work by default.
> sysext: Document Upholds= for starting units

- docs/_index.md
- docs/setup/security/audit.md
The default ignore rule is tricky because it needs to be removed first when setting up own rules. We should at least document this. We can also tweak the defaults independently from having docs (as long as the docs are updated).
See https://github.com/flatcar/coreos-overlay/pull/2545
> Document audit system usage

- docs/container-runtimes/use-a-custom-docker-or-containerd-version.md
- docs/provisioning/sysext/_index.md
The original idea was that our future Docker/containerd sysext is set up in /usr/lib/extensions/ but support for this location got removed: https://github.com/systemd/systemd/commit/de862276eddbbe76b436213b4d427205356d1886 Now we would have to use our /etc overlay to enable the sysext image by default. The user opt-out entry to disable it was also in /etc and this won't work anymore. Instead, the user should directly overwrite the entry to let it point to /dev/null.
> sysext: Document setting up a symlink to /dev/null to disable default

- docs/installing/cloud/aws-ec2.md
deleted the reference to AWS China AMI, they are private now
> Deleting reference to broken AWS China AMIs

- docs/reference/developer-guides/sdk-modifying-flatcar.md
coreos-modules needs to be rebuilt before coreos-kernel, because the kernel ebuild builds the initramfs and this bundles some of the built kernel modules.
The previous steps in the guide, also need an update because they have the same issue but I haven't fully understood how to correct them yet.
> dev-guides: fix order of kernel package compilation

- docs/provisioning/config-transpiler/getting-started.md
There are some differences when migration from CLC to Butane. Write them down with hints on how to approach them.
Closes https://github.com/flatcar/Flatcar/issues/968
> config-transpiler: Add CT to Butane migration docs

- docs/reference/developer-guides/sdk-modifying-flatcar.md
Hi. I came across the following documentation at https://www.flatcar.org/docs/latest/reference/developer-guides/sdk-modifying-flatcar/ and was contemplating whether it would be appropriate to modify the command ``branch="$(git branch -r -l | sed -n 's:origin/(flatcar-[0-9]+)$:\1:p' | sort | tail -n1)"`` to ``branch="$(git branch -r -l | awk -F'/' '/origin/flatcar-[0-9]+$/ {print $2}' | sort | tail -n1)"`` instead. I noticed that the former version produces an unnecessary leading whitespace. Thank you for your attention
Validate that the change made has no unforeseen side-effects.
> Strip unnecessary leading whitespace when fetching desired branch name

- docs/setup/customization/network-config-with-networkd.md
Updated the network-config-with-networkd.md file to include instructions on how to view all IP addresses assigned to a network interface. This addition will help users verify the success of their configuration.
> Update network-config-with-networkd.md to show way to see all IP addresses on an interface

- docs/setup/customization/using-nvidia.md
This change removes a note on NVIDIA drivers only working on AWS and Azure. This is now outdated as we have moved the installer to the generic image: https://github.com/flatcar/scripts/pull/932
> using-nvidia.md: Remove AWS/Azure as drivers are now generic

- docs/provisioning/sysext/_index.md
The Butane configuration is architecture dependent because it pre-populates the extensions with Ignition.
Add architecture identifiers and also recommend the shorter usage example that relies on the provided .conf sysupdate files.
> provisioning/sysext: Use architecture identifiers

- docs/setup/customization/using-nvidia.md
Adding a note about the feature implementation version. We could drop after the feature moves stable and has stayed in there for couple of Stable versions.
> using-nvidia: Add a note about the feature implementation version

- docs/provisioning/sysext/_index.md
- docs/setup/releases/update-strategies.md
- sysext: Add debugging commands
When unsure what files an image ships or why the image is not compatible
it can help to list the image contents or show the debug output from the
matching.
- Correct unshare mount command for listing /etc
Unshare expects a single command with arguments but the "sh -c" was
forgotten here.
Ran the command for the docker compose image.
> sysext: Add debugging commands

- docs/provisioning/sysext/_index.md
For the exploration of systemd-sysext images the systemd-dissect command provides many features and should be preferred over a custom mounting. Show some examples.
Ran the commands
> sysext: Use systemd-dissect command
